apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapp
  name: webapp-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: assets
    port: 81
    targetPort: 80
  selector:
    run: webapp
  type: LoadBalancer
  loadBalancerIP: 34.71.149.227
  externalTrafficPolicy: Local
