steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/proxyapp-nginx:latest || true
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/$PROJECT_ID/proxyapp-nginx:latest', '-t', 'gcr.io/$PROJECT_ID/proxyapp-nginx:latest', '.' ]
images:
- 'gcr.io/$PROJECT_ID/proxyapp-nginx:latest'
timeout: 3600s
